### ISSUE TITLE
1.10.0 is breaking in at least one of our environments. 

### ISSUE THREAD

**Issue by corbesero** [gmiranda23/ntp#135]
previous version was fine.
here is the error
the ntp cookbook is called from our base role

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/role_base/recipes/default.rb
================================================================================


LocalJumpError
--------------
no block given (yield)


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ntp/recipes/default.rb:115:in `block in from_file'
  /var/chef/cache/cookbooks/ntp/recipes/default.rb:112:in `from_file'
  /var/chef/cache/cookbooks/sncr_common_base/recipes/_ntp.rb:10:in `from_file'
  /var/chef/cache/cookbooks/sncr_common_base/recipes/default.rb:14:in `block in from_file'
  /var/chef/cache/cookbooks/sncr_common_base/recipes/default.rb:8:in `each'
  /var/chef/cache/cookbooks/sncr_common_base/recipes/default.rb:8:in `from_file'
  /var/chef/cache/cookbooks/role_base/recipes/_common.rb:52:in `from_file'
  /var/chef/cache/cookbooks/role_base/recipes/default.rb:9:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ntp/recipes/default.rb:

108:    action :run
109:    only_if { node['ntp']['sync_hw_clock'] && !(platform_family?('windows') || platform_family?('freebsd')) }
110:  end
111:  
112:  service node['ntp']['service'] do
113:    supports status: true, restart: true
114:    action [:enable, :start]
115>>   timeout 30
116:    retries 3
117:    retry_delay 5
118:  end
119:  
```

**Comment by tas50** [comment]
I'm adding a guard to only set that on Windows, but what version of Chef are you running?  I tested this on a suite of Linux variants without issue.

**Comment by corbesero** [comment]
This is breaking in our AWS environments, where we are using chef-client version 11.12.8 hitting an EC11 server from (predominantly) CentOS 6.[67] hosts.  We are stuck at that version of the chef-client because of some architectural and proxy behavior issues with the chef-client and our enterprise chef.

**Comment by tas50** [comment]
I pushed a new release up. Can you try that out and let me know if that fixed your issue.

**Comment by corbesero** [comment]
I was just able to test it this morning.  The new version (1.10.1) worked in the test environment where 1.10.0 was broken.

Thank you.
